---
pid: /var/src/lolgebra/shared/pids/thin.pid
log: /var/src/lolgebra/shared/log/thin.log
timeout: 30
socket: /var/sock/thin/thin.lolgebra.sock
max_conns: 1024
chdir: /var/src/lolgebra/current
rackup: /var/src/lolgebra/shared/system/config/rackup.ru
max_persistent_conns: 512
environment: production
servers: 3
onebyone: true
